version: '3.1'

services: 
  docker-mysql:
    container_name: docker-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mmr
      - MYSQL_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
  spring-docker-service:
    image: mmr-be-docker-service
    build:
      context: ./mmr-back-end
      dockerfile: ./Dockerfile
    depends_on:
      docker-mysql: 
        condition: service_healthy
    ports:
      - 8081:8080
    environment:
      - CATALINA_OPTS=-Dspring.profiles.active=container
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=mmr 
      - DATABASE_PORT=3306
  angular-docker-service:
    image: mmr-fe-docker-service
    build:
      context: ./mmr-front-end
      dockerfile: ./Dockerfile
    ports:
      - 4200:80